---
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx-ingress
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    # kubernetes.io/tls-acme: "true"
  hosts:
  - host: app.datetime.lreed.dev
    paths:
    - "/"
  tls:
  - secretName: datetime-ingress-tls
    hosts:
      - app.datetime.lreed.dev
